version: '2.4'

services:

    nfs:
        image: stlouisn/nfs:latest
        container_name: nfs
        hostname: nfs
        environment:
            - LC_ALL=C.UTF-8
            - TZ=America/Halifax
        restart: unless-stopped
#         volumes:
#             - 
#         cap_add:
#             - 
#         sysctls:
#             - 
        logging:
            driver: json-file
            options:
                max-size: "10M"
                max-file: "3"
#         healthcheck:
